### ISSUE TITLE
Support remove package version

### ISSUE THREAD

**Issue by AvihaiSam** [gorilla-co/s3pypi#103]
This is a feature request.

Please add `--remove` flag.

**Comment by mdwint** [comment]
This is not a feature I personally need, so I'm not stoked about the idea. If someone wants to work on it though, pull requests are welcome.

Instead of a `--remove` flag, I'd prefer a subcommand such as `s3pypi remove {package} {version}`.

In the meantime, if you want to remove a package, it would suffice to edit the `index.html` and remove the archive from S3.

**Comment by AvihaiSam** [comment]
I agree about the subcommand.
Editing the `index.html` is much more complex than having the subcommand...
